apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: uptime-kuma
  name: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
        - env:
            - name: PUID
              value: '1001'
            - name: PGID
              value: '1001'
            - name: TZ
              value: UTC
          image: louislam/uptime-kuma:1.23.15-alpine # {"$imagepolicy": "flux-system:uptime-kuma"}
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          name: uptime-kuma
          ports:
            - containerPort: 3001
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              memory: &memory 145Mi
            requests:
              cpu: 10m
              memory: *memory
          securityContext:
            allowPrivilegeEscalation: true
            privileged: false
          volumeMounts:
            - mountPath: /app/data
              name: uptime-kuma-data
      dnsConfig:
        options:
          - name: ndots
            value: '1'
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: uptime-kuma-data
          persistentVolumeClaim:
            claimName: uptime-kuma-data
